;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #32302f
foreground = #fbf1c7
red        = #CC241D
green      = #98971a
yellow     = #d79921
blue       = #458588
purple     = #b16286
teal       = #689d6a
orange     = #d65d0e
gray       = #a89984

[bar/common]
monitor = ${env:MONITOR}
width = 100%
height = 20pt
background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 0
padding-right = 1
separator = |
separator-foreground = ${colors.green}
font-0 = "Noto Sans Mono:Bold:pixelsize=12;2"
font-1 = "Font Awesome 6 Free Regular:Regular:pixelsize=12;2"
font-2 = "Font Awesome 6 Free Solid:Regular:pixelsize=12;2"
font-3 = "Font Awesome 6 Brands Regular:Regular:Pixelsize=12;2"
font-4 = "Noto Sans CJK JP:Bold:pixelsize=12;2"
font-5 = "Noto Sans CJK KR:Bold:pixelsize=12;2"
cursor-click = pointer
enable-ipc = true
bottom = true

[bar/primary]
inherit = bar/common
modules-left = i3
modules-right = player-mpris-tail pulseaudio date
tray-position = right

[bar/secondary]
inherit = bar/common
modules-left = i3
modules-right = cpu memory date

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
enable-click = true
format-padding = 1
index-sort = true
strip-wsnumbers = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;
ws-icon-deafult = 

label-visible = %name% %icon%
label-visible-padding = 1

label-focused = %name% %icon%
label-focused-background = ${colors.blue}
label-focused-foreground = ${colors.background}
label-focused-padding = 1

label-unfocused = %name% %icon%
label-unfocused-padding = 1

label-urgent = %name% %icon%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

label-separator = |
label-separator-foreground = ${colors.green}

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %mountpoint%%{F-} %percentage_used%%
label-mounted-foreground = ${colors.blue}
label-unmounted = %mountpoint%
label-unmounted-foreground = ${colors.green}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = ""
format-volume-prefix-foreground = ${colors.foreground}
format-volume = <ramp-volume> <label-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
label-volume = %percentage%%
label-muted = 
label-muted-foreground = ${colors.red}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.blue}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.blue}
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1
date = %D %I:%M %p
label = %date%
label-foreground = ${colors.foreground}

[module/player-mpris-tail]
type = custom/script
exec = ~/.config/polybar/player-mpris-tail.py -f '{:artist:t18:{artist}:}{:artist: - :}{:t20:{title}:}  %{A1:~/.config/polybar/player-mpris-tail.py previous -b vlc -b plasma-browser-integration:} ⏮ %{A} %{A1:~/.config/polybar/player-mpris-tail.py play-pause -b vlc -b plasma-browser-integration:} {icon-reversed} %{A} %{A1:~/.config/polybar/player-mpris-tail.py next -b vlc -b plasma-browser-integration:} ⏭ %{A}' -b vlc -b plasma-browser-integration --icon-playing=
tail = true

[settings]
screenchange-reload = true
pseudo-transparency = true

